# Generated by Django 5.2.8 on 2025-11-27 12:51

import core.models
import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("PROFILE_PHOTO", "Photo de profil"),
                            ("BIRTH_CERTIFICATE", "Acte de naissance"),
                            ("TRANSCRIPT", "Bulletin/Relevé ancien"),
                            ("ADMISSION_FOLDER", "Dossier d'admission"),
                            ("CV", "Curriculum Vitae (CV)"),
                            ("DIPLOMA", "Diplôme"),
                            ("ID_CARD", "CNI / Passeport"),
                            ("CONTRACT", "Contrat de travail"),
                            ("PROOF_OF_EMPLOYMENT", "Justificatif professionnel"),
                            ("OTHER", "Autre"),
                        ],
                        default="OTHER",
                        max_length=50,
                        verbose_name="Type de document",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Description"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=core.models.user_directory_path,
                        validators=[
                            core.validators.validate_file_size,
                            core.validators.validate_file_extension,
                        ],
                        verbose_name="Fichier",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
        ),
    ]
